/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  contractsSidebar: [{type: 'autogenerated', dirName: 'contracts'}],
  conceptsSidebar: [{type: 'autogenerated', dirName: 'concepts'}],
  howtoSidebar: [{type: 'autogenerated', dirName: 'howto'}],
  whitepaperSidebar: [{type: 'autogenerated', dirName: 'whitepaper'}],
  developersSidebar: [
    'developers/developers_index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'developers/01-Getting Started'}],
    },
    {
      type: 'category',
      label: 'REST API',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developers/02-REST API'}],
    },
    {
      type: 'category',
      label: 'MCP',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developers/03-MCP'}],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developers/04-SDK'}],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developers/05-Workflows'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;