/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  contractsSidebar: [{type: 'autogenerated', dirName: 'contracts'}],
  conceptsSidebar: [{type: 'autogenerated', dirName: 'concepts'}],
  howtoSidebar: [{type: 'autogenerated', dirName: 'howto'}],
  whitepaperSidebar: [{type: 'autogenerated', dirName: 'whitepaper'}],
  developersSidebar: [
    'developers/developers_index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'developers/Getting Started/quickstart-sdk',
        'developers/Getting Started/quickstart-rest',
        'developers/Getting Started/quickstart-mcp',
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsed: true,
      items: [
        'developers/SDK/installation',
        'developers/SDK/client-setup',
        'developers/SDK/reads-and-writes',
        'developers/SDK/react-hooks',
        'developers/SDK/subgraph',
        'developers/SDK/caller',
        'developers/SDK/amounts-and-dates',
        'developers/SDK/sdk-errors',
        'developers/SDK/export-map',
      ],
    },
    {
      type: 'category',
      label: 'REST API',
      collapsed: true,
      items: [
        'developers/REST API/authentication',
        'developers/REST API/chain-selection',
        'developers/REST API/rate-limits',
        'developers/REST API/read-endpoints',
        'developers/REST API/write-endpoints',
        'developers/REST API/errors',
        'developers/REST API/catalog',
      ],
    },
    {
      type: 'category',
      label: 'MCP',
      collapsed: true,
      items: [
        'developers/MCP/connection',
        'developers/MCP/tools-reference',
        'developers/MCP/x402-payments',
        'developers/MCP/write-workflow',
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'developers/05-Workflows'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;